[package]
name = "tea-actorx2-examples-actor"
version = { workspace = true }
edition = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
license-file = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
tea-sdk = { path = "../../..", features = ["wasm"] }
tea-actorx2-examples-codec = { path = "../codec" }
