[package]
name = "actorx-example-codec"
version = { workspace = true }
edition = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
license-file = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
publish = false

[dependencies]
tea-sdk = { version = "0.2.0-dev.1", path = "../../.." }
serde = { workspace = true }
