[workspace]
resolver = "2"
members = ["codecs/*", "actorx/actorx-*", "actorx/examples/*"]

[workspace.dependencies]
base64 = "0.13.0"
bincode = "1.2.0"
crossbeam = "0.8.2"
crossbeam-channel = "0.5.6"
dashmap = "5.4"
futures = "0.3.25"
hex = "0.4.0"
impl-trait-for-tuples = "0.2.2"
log = { version = "0.4.17", features = ["std", "serde"] }
num-derive = "0.3.3"
num-traits = "0.2.15"
parking_lot = "0.12.1"
primitive-types = { version = "0.12.1", features = ["serde"] }
prost = "0.11.0"
regex = { version = "1.7.0" }
serde = { version = "1.0.147", features = ["derive", "rc"] }
serde_bytes = "0.11.3"
serde_derive = "1.0.147"
serde_json = "1.0.87"
smallvec = { version = "1.9.0", features = [
    "serde",
    "write",
    "union",
    "const_generics",
    "const_new",
] }
thiserror = "1.0.22"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter"] }
tokio = { version = "1.21.2" }
once_cell = "1.17.0"
openssl = { version = "0.10", features = ["vendored"] }
wasmer = { version = "3.0.1", features = ["tracing"] }
wasmer-middlewares = "3.0.1"
wasmer-types = "3.0.1"
