[package]
name = "tea-wasm-client-actor-utils"
version = { workspace = true }
edition = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
license-file = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
tea-codec = { version = "0.2.0-dev.4", path = "../../codecs/tea-codec" }
tea-actorx-core = { version = "0.2.0-dev.4", path = "../../actorx/actorx-core" }
tea-actorx-runtime = { version = "0.2.0-dev.4", path = "../../actorx/actorx-runtime" }
tea-runtime-codec = { version = "0.2.0-dev.4", path = "../../codecs/runtime-codec" }

tea-wasm-actor-utils = { version = "0.2.0-dev.4", path = "../wasm-actor-utils", features = [
    "http",
] }

tea-system-actors = { version = "0.2.0-dev.4", path = "../../system-actors" }

serde = { workspace = true }
base64 = { workspace = true }
bincode = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
ed25519-dalek = { workspace = true }
log = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
prost = { workspace = true }
primitive-types = { workspace = true }
gluesql-core = { workspace = true }
hyper = { workspace = true }

mocktopus = { version = "0.7.0", optional = true }

[features]
nitro = []
simulator = []
__test = ["tea-runtime-codec/__test", "mocktopus"]
