[package]
name = "tea-actorx2-examples-codec"
version = { workspace = true }
edition = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
license-file = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
publish = false

[dependencies]
tea-sdk = { path = "../../.." }
serde = { workspace = true }
