[package]
name = "tea-actorx-examples-actor"
version = { workspace = true }
edition = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
license-file = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
thiserror = { workspace = true }
anyhow = { workspace = true }
tea-sdk = { path = "../../..", features = ["wasm"] }
tea-actorx-examples-codec = { path = "../codec" }

[dev-dependencies]
tokio = { version = "1.28.0", features = ["full"] }
tea-sdk = { path = "../../..", features = ["host"] }
