[package]
name = "actorx-example-actor"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
tea-sdk = { path = "../../..", features = ["wasm"] }
actorx-example-codec = { path = "../actorx-example-codec" }

[dev-dependencies]
tea-sdk = { path = "../../..", features = ["mock"] }
tokio = { workspace = true, features = ["full"] }
tracing-subscriber = { workspace = true }
actorx-example-host = { path = "../actorx-example-host" }
