[package]
name = "tea-wasm-actor-utils"
version = { workspace = true }
edition = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
license-file = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
tea-codec = { version = "0.2.0-dev.1", path = "../../codecs/tea-codec" }
tea-actorx-core = { version = "0.2.0-dev.1", path = "../../actorx/actorx-core" }
tea-actorx-host = { version = "0.2.0-dev.1", path = "../../actorx/actorx-host", optional = true }
tea-actorx-runtime = { version = "0.2.0-dev.1", path = "../../actorx/actorx-runtime" }
tea-tapp-common = { version = "0.2.0-dev.1", path = "../../codecs/tapp-common" }
tea-actor-txns = { version = "0.2.0-dev.1", path = "../../codecs/actor-txns" }
tea-solc-codec = { version = "0.2.0-dev.1", path = "../../codecs/solc-codec" }
tea-vmh-codec = { version = "0.2.0-dev.1", path = "../../codecs/vmh-codec" }
tea-runtime-codec = { version = "0.2.0-dev.1", path = "../../codecs/runtime-codec" }

tea-adapter-actor-codec = { version = "0.2.0-dev.1", path = "../../system-actors/adapter-actor" }
tea-crypto-actor-codec = { version = "0.2.0-dev.1", path = "../../system-actors/crypto-actor" }
tea-env-actor-codec = { version = "0.2.0-dev.1", path = "../../system-actors/env-actor" }
tea-http-actor-codec = { version = "0.2.0-dev.1", path = "../../system-actors/http-actor" }
tea-keyvalue-actor-codec = { version = "0.2.0-dev.1", path = "../../system-actors/keyvalue-actor" }
tea-layer1-actor-codec = { version = "0.2.0-dev.1", path = "../../system-actors/layer1-actor" }
tea-layer1-service-actor-codec = { version = "0.2.0-dev.1", path = "../../system-actors/layer1-service-actor" }
tea-libp2p-actor-codec = { version = "0.2.0-dev.1", path = "../../system-actors/libp2p-actor" }
tea-nitro-actor-codec = { version = "0.2.0-dev.1", path = "../../system-actors/nitro-actor" }
tea-persist-actor-codec = { version = "0.2.0-dev.1", path = "../../system-actors/persist-actor" }
tea-ra-actor-codec = { version = "0.2.0-dev.1", path = "../../system-actors/ra-actor" }
tea-replica-actor-codec = { version = "0.2.0-dev.1", path = "../../system-actors/replica-actor" }
tea-replica-service-actor-codec = { version = "0.2.0-dev.1", path = "../../system-actors/replica-service-actor" }
tea-state-receiver-codec = { version = "0.2.0-dev.1", path = "../../system-actors/state-receiver" }
tea-tappstore-actor-codec = { version = "0.2.0-dev.1", path = "../../system-actors/tappstore-actor" }
tea-tokenstate-actor-codec = { version = "0.2.0-dev.1", path = "../../system-actors/tokenstate-actor" }
tea-tokenstate-service-actor-codec = { version = "0.2.0-dev.1", path = "../../system-actors/tokenstate-service-actor" }

serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
ed25519-dalek = { workspace = true }
log = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
prost = { workspace = true }
primitive-types = { workspace = true }
gluesql-core = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
lazy_static = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
http = { workspace = true, optional = true }
http-body = { workspace = true, optional = true }
httparse = { workspace = true, optional = true }
bytes = { workspace = true, optional = true }

mocktopus = { version = "0.7.0", optional = true }

[features]
nitro = []
simulator = []
http = ["dep:http", "http-body", "httparse", "bytes"]
native = ["tea-actorx-host"]
__test = ["tea-vmh-codec/__test", "mocktopus"]
