[package]
name = "tea-wasm-actor-utils"
version = { workspace = true }
edition = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
license-file = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
tea-codec = { version = "0.3.0-dev.7", path = "../../codecs/tea-codec" }
tea-actorx = { version = "0.3.0-dev.7", path = "../../actorx", features = [
	"wasm",
] }
tea-runtime-codec = { version = "0.3.0-dev.7", path = "../../codecs/runtime-codec" }
tea-system-actors = { version = "0.3.0-dev.7", path = "../../system-actors" }
base64 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
ed25519-dalek = { workspace = true }
log = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
prost = { workspace = true }
primitive-types = { workspace = true }
gluesql-core = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
lazy_static = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
http = { workspace = true }
bytes = { workspace = true }

mocktopus = { workspace = true, optional = true }

[dev-dependencies]
rand = { workspace = true }

[features]
native = ["tea-actorx/host"]
__test = ["tea-runtime-codec/__test", "mocktopus"]
