[package]
name = "tea-wasm-actor-utils"
version = { workspace = true }
edition = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
license-file = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
tea-codec = { version = "0.2.0-dev.3", path = "../../codecs/tea-codec" }
tea-actorx-core = { version = "0.2.0-dev.3", path = "../../actorx/actorx-core" }
tea-actorx-host = { version = "0.2.0-dev.3", path = "../../actorx/actorx-host", optional = true }
tea-actorx-runtime = { version = "0.2.0-dev.3", path = "../../actorx/actorx-runtime" }
tea-tapp-common = { version = "0.2.0-dev.3", path = "../../codecs/tapp-common" }
tea-actor-txns = { version = "0.2.0-dev.3", path = "../../codecs/actor-txns" }
tea-solc-codec = { version = "0.2.0-dev.3", path = "../../codecs/solc-codec" }
tea-vmh-codec = { version = "0.2.0-dev.3", path = "../../codecs/vmh-codec" }
tea-runtime-codec = { version = "0.2.0-dev.3", path = "../../codecs/runtime-codec" }

tea-system-actors = { version = "0.2.0-dev.3", path = "../../system-actors" }

serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
ed25519-dalek = { workspace = true }
log = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
prost = { workspace = true }
primitive-types = { workspace = true }
gluesql-core = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
lazy_static = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
http = { workspace = true, optional = true }
http-body = { workspace = true, optional = true }
httparse = { workspace = true, optional = true }
bytes = { workspace = true, optional = true }

mocktopus = { version = "0.7.0", optional = true }

[features]
nitro = []
simulator = []
http = ["dep:http", "http-body", "httparse", "bytes"]
native = ["tea-actorx-host"]
__test = ["tea-vmh-codec/__test", "mocktopus"]
