[package]
name = "tea-system-actors"
version = { workspace = true }
edition = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
license-file = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
tea-codec = { version = "0.2.0-dev.4", path = "../codecs/tea-codec" }
tea-actorx-core = { version = "0.2.0-dev.4", path = "../actorx/actorx-core" }
tea-tapp-common = { version = "0.2.0-dev.4", path = "../codecs/tapp-common" }
tea-solc-codec = { version = "0.2.0-dev.4", path = "../codecs/solc-codec" }
tea-vmh-codec = { version = "0.2.0-dev.4", path = "../codecs/vmh-codec" }
tea-runtime-codec = { version = "0.2.0-dev.4", path = "../codecs/runtime-codec" }
tea-actor-txns = { version = "0.2.0-dev.4", path = "../codecs/actor-txns" }

serde = { workspace = true }
strum_macros = { workspace = true }

[features]
nitro = []
simulator = []
__test = []
