[package]
name = "tea-actorx2-examples-host"
version = { workspace = true }
edition = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
license-file = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
publish = false

[dependencies]
tea-sdk = { path = "../../..", features = ["host"] }
tea-actorx2-examples-codec = { path = "../codec" }
tokio = { workspace = true, features = ["full"] }

[build-dependencies]
tea-sdk = { path = "../../..", features = ["sign"] }
